//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusHelperApp.Main {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }



        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CampusHelperApp.Main.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainButton.
        /// </summary>
        internal static string MainButtonName {
            get {
                return ResourceManager.GetString("MainButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some main button tooltip.
        /// </summary>
        internal static string MainButtonTooltip {
            get {
                return ResourceManager.GetString("MainButtonTooltip", resourceCulture);
            }
        }
        internal static string SecondButtonName {
            get
            {
                return ResourceManager.GetString("SecondButtonName", resourceCulture);
            }
        }


        internal static string SecondButtonTooltip {
            get
            {
                return ResourceManager.GetString("SecondButtonTooltip", resourceCulture);
            }
        }


        internal static string ThirdButtonName
        {
            get
            {
                return ResourceManager.GetString("ThirdButtonName", resourceCulture);
            }
        }
        internal static string ThirdButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("ThirdButtonTooltip", resourceCulture);
            }
        }


        internal static string FourthButtonName
        {
            get
            {
                return ResourceManager.GetString("FourthButtonName", resourceCulture);
            }
        }
        internal static string FourthButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("FourthButtonTooltip", resourceCulture);
            }
        }

        internal static string FifthButtonName
        {
            get
            {
                return ResourceManager.GetString("FifthButtonName", resourceCulture);
            }
        }
        internal static string FifthButtonToolTip
        {
            get
            {
                return ResourceManager.GetString("FifthButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ribbon Panel.
        /// </summary>
        internal static string RibbonPanelName {
            get {
                return ResourceManager.GetString("RibbonPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribbon Tab.
        /// </summary>
        internal static string RibbonTabName {
            get {
                return ResourceManager.GetString("RibbonTabName", resourceCulture);
            }
        }

    }
}
